require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CourcesController do

  # This should return the minimal set of attributes required to create a valid
  # Cource. As you add validations to Cource, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all cources as @cources" do
      cource = Cource.create! valid_attributes
      get :index
      assigns(:cources).should eq([cource])
    end
  end

  describe "GET show" do
    it "assigns the requested cource as @cource" do
      cource = Cource.create! valid_attributes
      get :show, :id => cource.id.to_s
      assigns(:cource).should eq(cource)
    end
  end

  describe "GET new" do
    it "assigns a new cource as @cource" do
      get :new
      assigns(:cource).should be_a_new(Cource)
    end
  end

  describe "GET edit" do
    it "assigns the requested cource as @cource" do
      cource = Cource.create! valid_attributes
      get :edit, :id => cource.id.to_s
      assigns(:cource).should eq(cource)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Cource" do
        expect {
          post :create, :cource => valid_attributes
        }.to change(Cource, :count).by(1)
      end

      it "assigns a newly created cource as @cource" do
        post :create, :cource => valid_attributes
        assigns(:cource).should be_a(Cource)
        assigns(:cource).should be_persisted
      end

      it "redirects to the created cource" do
        post :create, :cource => valid_attributes
        response.should redirect_to(Cource.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cource as @cource" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cource.any_instance.stub(:save).and_return(false)
        post :create, :cource => {}
        assigns(:cource).should be_a_new(Cource)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cource.any_instance.stub(:save).and_return(false)
        post :create, :cource => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cource" do
        cource = Cource.create! valid_attributes
        # Assuming there are no other cources in the database, this
        # specifies that the Cource created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Cource.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => cource.id, :cource => {'these' => 'params'}
      end

      it "assigns the requested cource as @cource" do
        cource = Cource.create! valid_attributes
        put :update, :id => cource.id, :cource => valid_attributes
        assigns(:cource).should eq(cource)
      end

      it "redirects to the cource" do
        cource = Cource.create! valid_attributes
        put :update, :id => cource.id, :cource => valid_attributes
        response.should redirect_to(cource)
      end
    end

    describe "with invalid params" do
      it "assigns the cource as @cource" do
        cource = Cource.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cource.any_instance.stub(:save).and_return(false)
        put :update, :id => cource.id.to_s, :cource => {}
        assigns(:cource).should eq(cource)
      end

      it "re-renders the 'edit' template" do
        cource = Cource.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cource.any_instance.stub(:save).and_return(false)
        put :update, :id => cource.id.to_s, :cource => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cource" do
      cource = Cource.create! valid_attributes
      expect {
        delete :destroy, :id => cource.id.to_s
      }.to change(Cource, :count).by(-1)
    end

    it "redirects to the cources list" do
      cource = Cource.create! valid_attributes
      delete :destroy, :id => cource.id.to_s
      response.should redirect_to(cources_url)
    end
  end

end
